name: pytest

on:
    push:
      branches: [ main, dev,]
    pull_request:
      branches: [ main, dev,]

jobs:
  update:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
          cache: pip

      - name: Install requirements
        run: pip install -r requirements/test.txt

      - name: Run tests
        run: python -B -m pytest --cov=. --cov-report=xml
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}